# Generated by Django 2.2.15 on 2020-08-30 15:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ShortComment',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('content', models.CharField(max_length=200)),
                ('stars', models.CharField(max_length=5)),
                ('ts', models.DateTimeField()),
            ],
        ),
    ]
