# Generated by Selenium IDE
import pytest
import time
import json
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.common.action_chains import ActionChains
from selenium.webdriver.support import expected_conditions
from selenium.webdriver.support.wait import WebDriverWait
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.common.desired_capabilities import DesiredCapabilities


'''
如第一行自动生成的注释，其实是selenium IDE里面copy出来的，这个用户名密码登录，真没我们我们自己的那个登录页复杂

我现在就在想，如果强制了双因子认证，这自动化测试、爬虫的，哦，也能搞应该，要不1password那个咋实现的，所以说1password那个安全么...
'''

class TestShimologin():
  def setup_method(self, method):
    self.driver = webdriver.Chrome().fn
    self.vars = {}
  
  def teardown_method(self, method):
    # self.driver.quit()
    # 我承认我把这个去了就是为了看一眼
    pass
  
  def test_shimologin(self):
    self.driver.get("https://shimo.im/welcome")
    self.driver.set_window_size(1900, 1055)
    self.driver.find_element(By.CSS_SELECTOR, ".login-button").click()
    # 我承认我就是不饿能把我的密码放上来
    self.driver.find_element(By.NAME, "mobileOrEmail").send_keys("balabala")
    self.driver.find_element(By.NAME, "password").send_keys("kakakaka")
    self.driver.find_element(By.CSS_SELECTOR, ".submit").click()
    # 我承认这里其实应该写个断言，我特么上周刚和组员说的，我就先提交了，我看看自己到底有多懒，会不会自己后面加上断言
  
